version: "3.9"

services:
  db:
    image: postgres:15-alpine 
    container_name: focusflow_db
    restart: unless-stopped
    environment:
      POSTGRES_USER: focusflow
      POSTGRES_PASSWORD: focusflow
      POSTGRES_DB: focusflow
    ports:
      - "5432:5432"
    volumes:
      - ./postgres-data:/var/lib/postgresql/data
volumes:
  pg_data: