# backend/app/schemas/message.py

import uuid
from datetime import datetime
from pydantic import BaseModel

# Import the Enum from the ORM model to ensure consistency
from app.models.message import MessageRole

class MessageBase(BaseModel):
    """
    Base schema for a message, containing common fields.
    """
    role: MessageRole
    content: str

class MessageCreate(MessageBase):
    """
    Schema used for creating a new message internally.
    Inherits all fields from MessageBase.
    """
    pass

class Message(MessageBase):
    """
    Schema for representing a message in API responses.
    This includes fields that are generated by the database.
    """
    id: uuid.UUID
    created_at: datetime

    class Config:
        # Pydantic v2 compatibility: enables creating the schema from an ORM model instance.
        from_attributes = True
