import uuid
from datetime import datetime
from pydantic import BaseModel
from app.models.message import MessageRole

class MessageBase(BaseModel):
    """
    Base schema for a message, containing common fields.
    """
    role: MessageRole
    content: str

class MessageCreate(MessageBase):
    """
    Schema used for creating a new message internally.
    Inherits all fields from MessageBase.
    """
    pass

class Message(MessageBase):
    """
    Schema for representing a message in API responses.
    This includes fields that are generated by the database.
    """
    id: uuid.UUID
    created_at: datetime

    class Config:
        from_attributes = True
